# Recipe for generating (x, y, z) pairs from (count_x, count_y) of chessboard corners

In this notebook I show how I reached at a recipe to generate something like {(0, 0, 0), (0, 1, 0), (1, 0, 0), (1, 1, 0)} from a chessboard count tuple such as (2, 2) which means: 2 (inner) corners along the x axis, and 2 (inner) corners along the y axis.

In [6]:
import numpy as np

corners_size = (6, 4)

print("count of (inner) chessboard corners along the 'x' axis: ", corners_size[0])
print("count of (inner) chessboard corners along the 'y' axis: ", corners_size[1])

y_part_of_coordinate, x_part_of_coordinate = \
   np.mgrid[:corners_size[1], :corners_size[0]] 

print("\n'x' part of coordinates:\n", x_part_of_coordinate)
print("\n'y' part of coordinates:\n", y_part_of_coordinate)

count of (inner) chessboard corners along the 'x' axis:  6
count of (inner) chessboard corners along the 'y' axis:  4

'x' part of coordinates:
 [[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]

'y' part of coordinates:
 [[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]]


Now that we have the x part and the y parts separately, we need the z part in a similar fashion which is nothing but a zero matrix of the shame shape as both the x/y matrices. This can be done two ways, either using the nd.zeros following a shape of corners_size[::-1] or using nd.zeros_like. I choose the first approach:

In [7]:
z_part_of_coordinate = np.zeros(corners_size[::-1])

print("\n'z' part of coordinates:\n", z_part_of_coordinate)


'z' part of coordinates:
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


---------------------------------------
Now we combine all the dimensions into one array:

xyz_coordinates_separately = np.array([x_part_of_coordinate, y_part_of_coordinate, z_part_of_coordinate])

print('x/y/z coordinates each on its own in a 2-dimensional array, within one list:\n', xyz_coordinates_separately)

At level 0, there are 3, 2-dimensional arrays that can be seen at this point, each carrying floating-point numbers which represent the x, the y, and the z coordinates.

In order to transform that into coordinate pairs we use the np.dstack function:

In [10]:
xyz_pairs = np.dstack(xyz_coordinates_separately)

print('x/y/z pairs using "np.dstack":\n', xyz_pairs)

x/y/z pairs using "np.dstack":
 [[[ 0.  0.  0.]
  [ 1.  0.  0.]
  [ 2.  0.  0.]
  [ 3.  0.  0.]
  [ 4.  0.  0.]
  [ 5.  0.  0.]]

 [[ 0.  1.  0.]
  [ 1.  1.  0.]
  [ 2.  1.  0.]
  [ 3.  1.  0.]
  [ 4.  1.  0.]
  [ 5.  1.  0.]]

 [[ 0.  2.  0.]
  [ 1.  2.  0.]
  [ 2.  2.  0.]
  [ 3.  2.  0.]
  [ 4.  2.  0.]
  [ 5.  2.  0.]]

 [[ 0.  3.  0.]
  [ 1.  3.  0.]
  [ 2.  3.  0.]
  [ 3.  3.  0.]
  [ 4.  3.  0.]
  [ 5.  3.  0.]]]


We're almost there. All that is left to do is to remove the artifical boundaries or to flatten the array into a a list of ternary tuples. This is easily achieved using "np.reshape" while leaving the unknown or the automatic dimension as "-1":

In [12]:
objpoints = xyz_pairs.reshape((-1,3))

print('objpoints ready to be passed to OpenCV calibrateCamera:\n', objpoints)

objpoints ready to be passed to OpenCV calibrateCamera:
 [[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  0.  0.]
 [ 3.  0.  0.]
 [ 4.  0.  0.]
 [ 5.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  1.  0.]
 [ 2.  1.  0.]
 [ 3.  1.  0.]
 [ 4.  1.  0.]
 [ 5.  1.  0.]
 [ 0.  2.  0.]
 [ 1.  2.  0.]
 [ 2.  2.  0.]
 [ 3.  2.  0.]
 [ 4.  2.  0.]
 [ 5.  2.  0.]
 [ 0.  3.  0.]
 [ 1.  3.  0.]
 [ 2.  3.  0.]
 [ 3.  3.  0.]
 [ 4.  3.  0.]
 [ 5.  3.  0.]]


## One line of code

It is possible to arrive at the same result above using a single line of code, which is how this recipe is used in my code.

In [18]:
objpoints_direct = \
    np.dstack(np.concatenate(( \
        np.mgrid[:corners_size[1],:corners_size[0]][::-1], \
        [np.zeros(corners_size[::-1])] \
    ))).reshape((-1,3))
    
print('objpoints, just as before:\n', objpoints_direct)

objpoints, just as before:
 [[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  0.  0.]
 [ 3.  0.  0.]
 [ 4.  0.  0.]
 [ 5.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  1.  0.]
 [ 2.  1.  0.]
 [ 3.  1.  0.]
 [ 4.  1.  0.]
 [ 5.  1.  0.]
 [ 0.  2.  0.]
 [ 1.  2.  0.]
 [ 2.  2.  0.]
 [ 3.  2.  0.]
 [ 4.  2.  0.]
 [ 5.  2.  0.]
 [ 0.  3.  0.]
 [ 1.  3.  0.]
 [ 2.  3.  0.]
 [ 3.  3.  0.]
 [ 4.  3.  0.]
 [ 5.  3.  0.]]
